//! Evidence — where an expected value came from, and whether it was met.
//!
//! The single rule this module exists to enforce: **an expected value may never
//! be produced by the code under test.** A number generated by the thing being
//! checked proves nothing, and a system that scores itself on such numbers is
//! confidently wrong, which is worse than unscored.

use crate::credibility::Tier;

/// Where an expected value came from. The schema rejects a fixture whose
/// provenance is the implementation, so this enum is the gate.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Provenance {
    /// A closed form derived independently, paired with a second route.
    IndependentDerivation,
    /// A published table or reference implementation, cited to the page.
    PublishedSource,
    /// An independent tool run by a person. This is what MATLAB is for, and it
    /// is why the legacy tool is a second opinion rather than a liability.
    IndependentTool,
    /// A physical bound or a conservation law that must hold.
    PhysicalBound,
    /// A snapshot of what this code currently produces. Detects change, never
    /// correctness — accepted only as a regression guard, never as validation.
    SelfSnapshot,
    /// A value an agent produced. Always rejected; present in the enum so the
    /// rejection is a matched case rather than a missing one.
    AgentGenerated,
}

impl Provenance {
    /// The highest tier a fixture with this provenance can support.
    pub const fn highest_tier(self) -> Tier {
        match self {
            Provenance::IndependentDerivation => Tier::APlus,
            Provenance::PublishedSource => Tier::A,
            Provenance::IndependentTool => Tier::B,
            Provenance::PhysicalBound => Tier::C,
            Provenance::SelfSnapshot => Tier::Unset,
            Provenance::AgentGenerated => Tier::Unset,
        }
    }
    /// Whether this provenance may be used as validation at all.
    pub const fn is_external_oracle(self) -> bool {
        matches!(
            self,
            Provenance::IndependentDerivation
                | Provenance::PublishedSource
                | Provenance::IndependentTool
                | Provenance::PhysicalBound
        )
    }
    pub const fn name(self) -> &'static str {
        match self {
            Provenance::IndependentDerivation => "independent-derivation",
            Provenance::PublishedSource => "published-source",
            Provenance::IndependentTool => "independent-tool",
            Provenance::PhysicalBound => "physical-bound",
            Provenance::SelfSnapshot => "self-snapshot",
            Provenance::AgentGenerated => "agent-generated",
        }
    }
    pub fn from_name(s: &str) -> Option<Provenance> {
        Some(match s {
            "independent-derivation" => Provenance::IndependentDerivation,
            "published-source" => Provenance::PublishedSource,
            "independent-tool" => Provenance::IndependentTool,
            "physical-bound" => Provenance::PhysicalBound,
            "self-snapshot" => Provenance::SelfSnapshot,
            "agent-generated" => Provenance::AgentGenerated,
            _ => return None,
        })
    }
}

/// One expected value, with the source that produced it.
#[derive(Clone, Copy, Debug)]
pub struct Fixture {
    /// A short label, so a failing row names itself.
    pub label: &'static str,
    /// The expected value, in the output's declared unit.
    pub expected: f64,
    /// Relative tolerance. Widening one is a gate change with two reviewers,
    /// because the commonest way a gate stops meaning anything is somebody
    /// widening a tolerance to get green.
    pub tolerance: f64,
    pub provenance: Provenance,
    /// The identifier of a row in `sources/`, never a free-text string.
    pub source: &'static str,
}

/// The result of checking one fixture.
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum Verdict {
    /// Within tolerance.
    Pass { relative_error: f64 },
    /// Outside tolerance. A physics disagreement, not a build failure — it goes
    /// to the node owner, and the tolerance is not the thing to change.
    Fail { got: f64, expected: f64, relative_error: f64, tolerance: f64 },
    /// The node refused to run on this fixture's case.
    Refused,
    /// The fixture exists and has not been executed in this run.
    NotRun,
}

impl Verdict {
    pub fn passed(self) -> bool {
        matches!(self, Verdict::Pass { .. })
    }
}

impl Fixture {
    /// Check a computed value against this fixture.
    pub fn check(&self, got: f64) -> Verdict {
        let e = self.expected;
        let err = if e == 0.0 {
            crate::units::pmath::abs(got)
        } else {
            crate::units::pmath::abs((got - e) / e)
        };
        if err <= self.tolerance {
            Verdict::Pass { relative_error: err }
        } else {
            Verdict::Fail { got, expected: e, relative_error: err, tolerance: self.tolerance }
        }
    }
}
