//! The translator's output for the worked example, held as a golden file the
//! kernel compiles and runs (crates/vleo-core/tests/the_translated_example_runs.rs).
//!
//! No node of this design carries a method until its owner sends one, so
//! without this nothing in the pipeline would ever compile what the translator
//! writes. The example is the one every node form shows; its Rust is kept here
//! byte for byte, and a translator change that alters it fails this test until
//! the golden is written again on purpose:
//!
//!     VLEO_GOLDEN=write cargo test -p vleo-sheet --test the_translator_writes_the_example

use std::path::PathBuf;
use vleo_sheet::{example, method};

#[test]
fn the_example_translates_to_the_golden_file() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let golden = root.join("crates/vleo-core/tests/golden/example_method.rs");
    let sig = method::Signature {
        inputs: vec![("r".into(), method::quantity_dim("Length").unwrap())],
        output: method::quantity_dim("Velocity").unwrap(),
        publishes: Vec::new(),
    };
    let p = method::compile(example::METHOD, &sig).expect("the example checks");
    let rust = method::to_rust(
        &p,
        "example_orbit_speed",
        "vallado2013",
        example::METHOD,
        &["r".to_string()],
    );
    let rust = vleo_sheet::emit::rustfmt_standalone(&rust);
    if std::env::var("VLEO_GOLDEN").as_deref() == Ok("write") {
        std::fs::write(&golden, &rust).unwrap();
    }
    let have = std::fs::read_to_string(&golden).unwrap_or_default();
    assert_eq!(
        have, rust,
        "the translator's output for the worked example changed. If that is intended, \
         write the golden again (see this file's header) and review the diff: every node \
         with a method is translated by the same rules."
    );
}

/// Every construct of the language at once — a loop that sets, a loop that
/// settles or refuses, a call into the kernel, a chain of
/// branches, a table, a list read by entry, by length, by `for … in` and as a
/// row of `interp` (and read past its end, at 4.5), powers written and
/// computed, each family of function —
/// translated, and the interpreter's answers at a spread of inputs written
/// beside it for the kernel test to hold the translation to, bit for bit.
const EVERYTHING: &str = "\
# Not physics: a method that uses every construct, for the translator.
if x < 0 then
  refuse \"x must not be negative\"
end
let total = 0
for n = 1 to 12
  set total = total + x ^ n / n
end
const EDGES = [0.5, 1, 2, 4] [1]
let band = 1
for edge in EDGES
  if x >= edge then
    set band = band + 1
  end
end
let lists = band + EDGES[floor(x) + 1] + interp(x, EDGES, [3, 1, 4, 1] [1]) + len(EDGES)
let h = x + 1
while h > 0.001 at most 12 times
  set h = h / 2
end
let t : Ratio = interp(x, [0, 0.5, 1, 4] [1], [1, 2, 0.5, 3] [1])
let a = sqrt(x + 1) + cbrt(x) + ln(x + 2) + exp(-x) + log10(x + 1) + log2(x + 1)
let b = sin(x) * cos(x) + tan(x / 10) + atan(x) + atan2(x, 1) + sinh(x / 5) + cosh(x / 5) + tanh(x)
let c = min(x, 2) + max(x, 0.5) + abs(0 - x) + hypot(x, 1) + fmod(x + 7, 3) + erf(x) + erfc(x)
let d = floor(x * 3) + ceil(x) + round(x * 2) + wrap_2pi(x * 7) + wrap_pi(x * 7) + pow(x + 1, 2.5) + (x + 1) ^ (x / 4)
let e = asin(min(x, 1)) + acos(min(x, 1)) + PI
let k = thermosphere_scale_height((x + 200) * 1000 [m], 1000 [K]) / 1e5 [m] + solar_cycle_mean(x * 86400 [s], (x + 30) * 86400 [s]) / 100
if x > 3 and not (x > 3.5) then
  return total + t + h + lists
else if x > 2 or x == 1.25 then
  return a + b + h + lists
else
  return (c + d + e + k) / (x + 1) + lists
end";

pub const EVERYTHING_POINTS: &[f64] = &[0.0, 0.1, 0.5, 1.0, 1.25, 1.7, 2.5, 3.2, 3.7, 4.5, -1.0];

#[test]
fn every_construct_translates_and_the_golden_holds_the_interpreters_answers() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let sig = method::Signature {
        inputs: vec![("x".into(), method::quantity_dim("Ratio").unwrap())],
        output: method::quantity_dim("Ratio").unwrap(),
        publishes: Vec::new(),
    };
    let p = method::compile(EVERYTHING, &sig).unwrap_or_else(|e| panic!("{e:?}"));
    let rust = vleo_sheet::emit::rustfmt_standalone(&method::to_rust(
        &p,
        "every_construct",
        "none — a translator test",
        EVERYTHING,
        &["x".to_string()],
    ));
    // What the interpreter gives at each point, as the bits of an answer or
    // the word for a refusal.
    let mut expect = String::from(
        "# GENERATED by crates/vleo-sheet/tests/the_translator_writes_the_example.rs:\n\
         # the interpreter's answers for every_construct, one input per line.\n",
    );
    for x in EVERYTHING_POINTS {
        let o = method::run(&p, &[("x".to_string(), *x)]);
        let v = match o {
            Ok(method::Outcome::Answer(v)) => format!("{:016x}", v.to_bits()),
            Ok(method::Outcome::Refused { .. }) => "refused".into(),
            Err(_) => "degenerate".into(),
        };
        expect.push_str(&format!("{x:?} {v}\n"));
    }
    let g1 = root.join("crates/vleo-core/tests/golden/every_construct.rs");
    let g2 = root.join("crates/vleo-core/tests/golden/every_construct.expect");
    if std::env::var("VLEO_GOLDEN").as_deref() == Ok("write") {
        std::fs::write(&g1, &rust).unwrap();
        std::fs::write(&g2, &expect).unwrap();
    }
    assert_eq!(
        std::fs::read_to_string(&g1).unwrap_or_default(),
        rust,
        "the translation changed"
    );
    assert_eq!(
        std::fs::read_to_string(&g2).unwrap_or_default(),
        expect,
        "the interpreter's answers changed"
    );
}

/// A method that publishes two members beside its answer, and refuses below
/// zero: the translation the kernel compiles, and the interpreter's answers it
/// must reproduce member by member.
pub const PUBLISHING: &str = "\
if x < 0 then
  refuse \"below zero\"
end
let s = x * x
publish Root = sqrt(x)
publish Square = s
return s + 1";

#[test]
fn a_publishing_method_translates_and_the_golden_holds_every_member() {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../..");
    let ratio = method::quantity_dim("Ratio").unwrap();
    let sig = method::Signature {
        inputs: vec![("x".into(), ratio)],
        output: ratio,
        // Declared Square first: the translation returns members in the
        // sheet's order, not the order the method publishes them in.
        publishes: vec![("Square".into(), ratio), ("Root".into(), ratio)],
    };
    let p = method::compile(PUBLISHING, &sig).unwrap_or_else(|e| panic!("{e:?}"));
    let order = ["Square".to_string(), "Root".to_string()];
    let rust = vleo_sheet::emit::rustfmt_standalone(&method::to_rust_publishing(
        &p,
        "publishing",
        "none — a translator test",
        PUBLISHING,
        &["x".to_string()],
        &order,
    ));
    let mut expect = String::from(
        "# GENERATED by crates/vleo-sheet/tests/the_translator_writes_the_example.rs:\n\
         # the interpreter's answers for publishing — the answer, then Square and Root.\n",
    );
    for x in [0.0, 0.25, 1.0, 2.0, 9.5, -1.0] {
        let line = match method::run_all(&p, &[("x".to_string(), x)]) {
            Ok((method::Outcome::Answer(v), m)) => {
                let bits = |n: &str| {
                    let v = m.iter().find(|(k, _)| k == n).map(|(_, v)| *v).unwrap();
                    format!("{:016x}", v.to_bits())
                };
                format!("{:016x} {} {}", v.to_bits(), bits("Square"), bits("Root"))
            }
            Ok((method::Outcome::Refused { .. }, _)) => "refused".into(),
            Err(_) => "degenerate".into(),
        };
        expect.push_str(&format!("{x:?} {line}\n"));
    }
    let g1 = root.join("crates/vleo-core/tests/golden/publishing.rs");
    let g2 = root.join("crates/vleo-core/tests/golden/publishing.expect");
    if std::env::var("VLEO_GOLDEN").as_deref() == Ok("write") {
        std::fs::write(&g1, &rust).unwrap();
        std::fs::write(&g2, &expect).unwrap();
    }
    assert_eq!(
        std::fs::read_to_string(&g1).unwrap_or_default(),
        rust,
        "the translation changed"
    );
    assert_eq!(
        std::fs::read_to_string(&g2).unwrap_or_default(),
        expect,
        "the interpreter's answers changed"
    );
}
