//! Releases and what ships: the version, the kit, guides, CODEOWNERS, bundles.

use super::*;

pub(super) fn cmd_codeowners(root: &Path) -> Result<(), String> {
    let tree = load(root)?;
    let teams = read_teams(root)?;
    let handles = |who: &[String]| who.join(" ");
    let mut o = String::new();
    o.push_str(
        "# GENERATED by `cargo xtask codeowners` from areas/teams.toml and the owner\n\
         # field on each node sheet. Do not edit: change the teams there, or a\n\
         # sheet's owner, and regenerate.\n\
         #\n\
         # The maintainers own what is shared, because a defect there reaches every\n\
         # node at once. The frontend, backend and data teams own their parts, and\n\
         # contract/ is owned by both sides. Each subsystem's developers own its nodes.\n\n\
         # team: maintainers\n",
    );
    let m = handles(&teams.maintainers);
    for path in [
        "/crates/",
        "/xtask/",
        "/tools/",
        "/layers/",
        "/cases/",
        "/sources/",
        "/web/",
        "/docs/",
        "/areas/",
        "/bundles/",
        "/contract/",
        "/.github/",
        "/AGENTS.md",
        "/CONTRIBUTING.md",
        "/CODEOWNERS",
        "/Cargo.toml",
        "/Cargo.lock",
    ] {
        o.push_str(&format!("{path:<26}{m}\n"));
    }
    // The three parts, over the maintainers on their own paths. contract/ is
    // where the frontend and the backend meet, so both own it; its file
    // formats are the data team's as well. GitHub asks ANY owner listed on a
    // path, not one of each — so "both sides review the contract" is a review
    // rule in CONTRIBUTING.md, which this makes sure reaches both.
    let part = |name: &str| {
        teams
            .parts
            .get(name)
            .cloned()
            .unwrap_or_else(|| teams.maintainers.clone())
    };
    let both = |names: &[&str]| {
        let mut who: Vec<String> = names.iter().flat_map(|n| part(n)).collect();
        who.sort();
        who.dedup();
        who
    };
    for (label, owners, paths) in [
        (
            "frontend",
            both(&["frontend"]),
            &[
                "/web/",
                "/panels/",
                "/tools/panel_check.py",
                "/tools/panel_review.py",
                "/tools/mock_engine.py",
                "/tools/mock_check.py",
            ][..],
        ),
        (
            "backend",
            both(&["backend"]),
            &[
                "/crates/vleo-units/",
                "/crates/vleo-core/",
                "/crates/vleo-bus/",
                "/crates/vleo-modules/",
                "/crates/vleo-sheet/",
                "/crates/vleo-server/",
                "/crates/vleo-daemon/",
                "/crates/vleo-cli/",
                "/xtask/",
            ][..],
        ),
        (
            "data",
            both(&["data"]),
            &[
                "/crates/vleo-data/",
                "/crates/vleo-files/",
                "/crates/vleo-kinds/",
                "/bundles/",
            ][..],
        ),
        (
            "the contract: frontend and backend",
            both(&["frontend", "backend"]),
            &["/contract/"][..],
        ),
        (
            "the file formats: frontend, backend and data",
            both(&["frontend", "backend", "data"]),
            &["/contract/formats/"][..],
        ),
    ] {
        o.push_str(&format!("\n# team: {label}\n"));
        for path in paths {
            o.push_str(&format!("{path:<26}{}\n", handles(&owners)));
        }
    }
    // Node folders by the team that answers for them. They come after the
    // shared paths: in CODEOWNERS the last matching rule wins.
    let mut by_owner: BTreeMap<&str, Vec<String>> = BTreeMap::new();
    let mut seen = std::collections::BTreeSet::new();
    for sh in tree.ordered() {
        if seen.insert((sh.crate_name.clone(), sh.folder.clone())) {
            by_owner
                .entry(sh.owner.as_str())
                .or_default()
                .push(format!("/crates/{}/nodes/{}/", sh.crate_name, sh.folder));
        }
    }
    let mut unowned = Vec::new();
    for (owner, paths) in &by_owner {
        let Some(who) = teams.developers.get(*owner) else {
            unowned.push(format!("{owner} ({} node(s))", paths.len()));
            continue;
        };
        o.push_str(&format!("\n# team: {owner} developers\n"));
        for path in paths {
            o.push_str(&format!("{path} {}\n", handles(who)));
        }
    }
    if !unowned.is_empty() {
        return Err(format!(
            "areas/teams.toml has no developer team for: {}. Add one, so no node falls \
             outside review.",
            unowned.join(", ")
        ));
    }

    // GitHub's one documented limit on this file, checked from
    // github/docs@main: "CODEOWNERS files must be under 3 MB in size. A
    // CODEOWNERS file over this limit will not be loaded, which means that
    // code owner information is not shown and the appropriate code owners
    // will not be requested to review changes in a pull request." No maximum
    // number of rules is stated anywhere in that page.
    //
    // Worth a check rather than a note because of how it fails: over the
    // limit the file is ignored in full and every pull request looks like one
    // with no owners, which is the same green as a pull request whose owners
    // all approved. One row costs about 66 bytes, so 3 MB is around 47,000 of
    // them and a 1,329-row tree uses 3% of it — but the tree is the thing that
    // grows, and this is the check that notices.
    const CODEOWNERS_LIMIT: usize = 3 * 1024 * 1024;
    if o.len() >= CODEOWNERS_LIMIT {
        return Err(format!(
            "the generated CODEOWNERS is {} bytes and GitHub ignores the file entirely at \
             3 MB. Over the limit every pull request shows no owners, which looks exactly \
             like a pull request whose owners approved. Consolidate rows onto wildcard \
             patterns per crate before writing this.",
            o.len()
        ));
    }
    fs::write(root.join("CODEOWNERS"), &o).map_err(|e| e.to_string())?;
    println!(
        "codeowners: {} lines, {} KB of the 3 MB GitHub will load ({}%)",
        o.lines().count(),
        o.len() / 1024,
        o.len() * 100 / CODEOWNERS_LIMIT
    );
    Ok(())
}

/// The teams areas/teams.toml declares.
struct Teams {
    maintainers: Vec<String>,
    /// frontend, backend and data — see areas/teams.toml.
    parts: BTreeMap<String, Vec<String>>,
    developers: BTreeMap<String, Vec<String>>,
}

fn read_teams(root: &Path) -> Result<Teams, String> {
    let path = root.join("areas/teams.toml");
    let text = fs::read_to_string(&path).map_err(|e| format!("areas/teams.toml: {e}"))?;
    let v: toml::Value = text.parse().map_err(|e| format!("areas/teams.toml: {e}"))?;
    let list = |x: Option<&toml::Value>, what: &str| -> Result<Vec<String>, String> {
        let items = x
            .and_then(|a| a.as_array())
            .ok_or_else(|| format!("areas/teams.toml: {what} is not a list of handles"))?;
        let who: Vec<String> = items
            .iter()
            .map(|h| h.as_str().unwrap_or("").to_string())
            .collect();
        if who.is_empty() || who.iter().any(|h| !h.starts_with('@') || h.len() < 2) {
            return Err(format!(
                "areas/teams.toml: {what} must name at least one GitHub handle, each written @name"
            ));
        }
        Ok(who)
    };
    let maintainers = list(
        v.get("maintainers").and_then(|m| m.get("members")),
        "[maintainers] members",
    )?;
    let mut developers = BTreeMap::new();
    for (team, who) in v
        .get("developers")
        .and_then(|d| d.as_table())
        .ok_or("areas/teams.toml has no [developers] table")?
    {
        developers.insert(
            team.clone(),
            list(Some(who), &format!("[developers] {team}"))?,
        );
    }
    let mut parts = BTreeMap::new();
    for (name, who) in v
        .get("parts")
        .and_then(|d| d.as_table())
        .into_iter()
        .flatten()
    {
        if !matches!(name.as_str(), "frontend" | "backend" | "data") {
            return Err(format!(
                "areas/teams.toml: [parts] {name} is not one of the three parts — frontend, backend, data"
            ));
        }
        parts.insert(name.clone(), list(Some(who), &format!("[parts] {name}"))?);
    }
    Ok(Teams {
        maintainers,
        parts,
        developers,
    })
}

pub(super) fn cmd_bundle(root: &Path, args: &[&str]) -> Result<(), String> {
    match args.first().copied() {
        Some("publish") => {
            let dir = args
                .get(1)
                .map(PathBuf::from)
                .ok_or("usage: cargo xtask bundle publish <dir>")?;
            let b = vleo_data::load_bundle(&dir)?;
            let computed = vleo_data::hash_files(&dir, &b.manifest.files)?;
            let mp = dir.join("manifest.toml");
            let text = fs::read_to_string(&mp).map_err(|e| e.to_string())?;
            let mut out = String::new();
            for line in text.lines() {
                if line.trim_start().starts_with("content_hash") {
                    out.push_str(&format!("content_hash = \"{computed}\"\n"));
                } else {
                    out.push_str(line);
                    out.push('\n');
                }
            }
            fs::write(&mp, out).map_err(|e| e.to_string())?;
            println!(
                "published {}@{} — {}",
                b.manifest.name, b.manifest.version, computed
            );
            println!("A published version is never edited. A correction is a new version.");
            Ok(())
        }
        Some("verify") | None => {
            let dir = root.join("bundles");
            let mut n = 0;
            let mut bad = 0;
            for e in fs::read_dir(&dir).map_err(|e| e.to_string())? {
                let p = e.map_err(|e| e.to_string())?.path();
                if !p.is_dir() {
                    continue;
                }
                for v in fs::read_dir(&p).map_err(|e| e.to_string())? {
                    let vp = v.map_err(|e| e.to_string())?.path();
                    if !vp.join("manifest.toml").is_file() {
                        continue;
                    }
                    n += 1;
                    let b = vleo_data::load_bundle(&vp)?;
                    if b.verified {
                        println!(
                            "  \x1b[32mok\x1b[0m   {}@{} {}",
                            b.manifest.name, b.manifest.version, b.manifest.content_hash
                        );
                    } else {
                        bad += 1;
                        println!(
                            "  \x1b[31mFAIL\x1b[0m {}@{} — {}",
                            b.manifest.name,
                            b.manifest.version,
                            b.refusal.unwrap_or_default()
                        );
                    }
                }
            }
            println!("{n} bundle(s), {bad} refused");
            if bad > 0 {
                return Err("a tampered byte is refused, never warned about".into());
            }
            Ok(())
        }
        Some(other) => Err(format!("unknown bundle command '{other}'")),
    }
}

/// The variable register.
///
/// Generated from the sheets, like everything else. A register maintained by
/// hand drifts from the tree within a week, and then it is worse than absent:
/// somebody will trust it.
/// The de-risking narrative: every recorded change and every risk, laid out
/// from the sheets. Two files, one to read and one for a spreadsheet.
pub(super) fn cmd_derisk(root: &Path, _args: &[&str]) -> Result<(), String> {
    let tree = load(root)?;
    let md = vleo_sheet::derisk::narrative_md(&tree);
    let csv = vleo_sheet::derisk::narrative_csv(&tree);
    let a = write_if_changed(&root.join("docs/DERISK_NARRATIVE.md"), &md)?;
    let b = write_if_changed(&root.join("docs/derisking.csv"), &csv)?;
    let (changes, starts) = vleo_sheet::derisk::narrative(&tree);
    let reg = vleo_sheet::derisk::register(&tree);
    println!(
        "derisk: {} change(s), {} starting belief(s), {} risk(s) registered, {} open — {}",
        changes.len(),
        starts.len(),
        reg.len(),
        reg.iter().filter(|r| r.now != "closed").count(),
        if a || b {
            "docs/DERISK_NARRATIVE.md and docs/derisking.csv written"
        } else {
            "nothing to write"
        }
    );
    Ok(())
}

/// The workspace version, as `Cargo.toml` states it.
pub(super) fn workspace_version(root: &Path) -> Result<String, String> {
    let text =
        fs::read_to_string(root.join("Cargo.toml")).map_err(|e| format!("Cargo.toml: {e}"))?;
    let v: toml::Value = text.parse().map_err(|e| format!("Cargo.toml: {e}"))?;
    v.get("workspace")
        .and_then(|w| w.get("package"))
        .and_then(|p| p.get("version"))
        .and_then(|x| x.as_str())
        .map(str::to_string)
        .ok_or_else(|| "Cargo.toml has no [workspace.package] version".into())
}

/// A RELEASE STAMPS THE BELIEFS IT CARRIES. Every node version recorded since
/// the last release says `next`; this names them with the release that ships
/// them, so a node's page and a saved result can say which release first held
/// each belief — and why the one before it was replaced.
/// THE TOOL, FOR A TEAM MEMBER, WITHOUT THE REPOSITORY.
///
/// The daemon reads its web face, the tree and every node's page at run time,
/// so the two programs alone do not run. A kit is those programs beside exactly
/// the files they read — nothing else: no git history, no generators, no
/// kernel source. The team uses it and sends back node forms; nothing in it is
/// ever edited, and their case and results live under `~/.vleo/`, outside it,
/// so the next kit replaces this one without losing either.
pub(super) fn cmd_kit(root: &Path, args: &[&str]) -> Result<(), String> {
    let after = |flag: &str| {
        args.iter()
            .position(|a| *a == flag)
            .and_then(|i| args.get(i + 1))
            .map(PathBuf::from)
    };
    let version = workspace_version(root)?;
    let bin = after("--bin").unwrap_or_else(|| root.join("target").join("release"));
    let out = after("--out").unwrap_or_else(|| root.join("dist").join(format!("vleo-{version}")));
    let exe = |name: &str| {
        [name.to_string(), format!("{name}.exe")]
            .into_iter()
            .map(|n| bin.join(n))
            .find(|p| p.is_file())
    };
    // `--files-only`: the files the tool reads and nothing that runs — what
    // the Python package carries beside its own engine.
    let files_only = args.contains(&"--files-only");
    let wanted: &[&str] = if files_only {
        &[]
    } else {
        &["vleo-daemon", "vleo"]
    };
    let programs: Vec<PathBuf> = wanted
        .iter()
        .map(|n| {
            exe(n).ok_or_else(|| {
                format!(
                    "no {n} in {} — build the programs first: \
                     cargo build --release -p vleo-daemon -p vleo-cli",
                    bin.display()
                )
            })
        })
        .collect::<Result<_, _>>()?;
    if out.exists() {
        fs::remove_dir_all(&out).map_err(|e| format!("{}: {e}", out.display()))?;
    }
    fs::create_dir_all(&out).map_err(|e| e.to_string())?;

    fn copy_tree(from: &Path, to: &Path) -> Result<usize, String> {
        let mut n = 0;
        fs::create_dir_all(to).map_err(|e| format!("{}: {e}", to.display()))?;
        for e in fs::read_dir(from).map_err(|e| format!("{}: {e}", from.display()))? {
            let p = e.map_err(|e| e.to_string())?.path();
            let dest = to.join(p.file_name().unwrap());
            if p.is_dir() {
                n += copy_tree(&p, &dest)?;
            } else {
                fs::copy(&p, &dest).map_err(|e| format!("{}: {e}", p.display()))?;
                n += 1;
            }
        }
        Ok(n)
    }
    // What the daemon reads, and only that. The design itself travels as its
    // files, `design/`, which the daemon reads as it reads them in a checkout.
    let mut files = 0;
    for dir in ["web", "bundles", "matlab/reference"] {
        let from = root.join(dir);
        if from.is_dir() {
            files += copy_tree(&from, &out.join(dir))?;
        }
    }
    fs::create_dir_all(out.join("docs")).map_err(|e| e.to_string())?;
    fs::copy(root.join("docs/manual.toml"), out.join("docs/manual.toml"))
        .map_err(|e| format!("docs/manual.toml: {e}"))?;
    files += 1;
    // The role guides travel with the tool: a user reads docs/roles/user.html
    // without the repository.
    if root.join("docs/roles").is_dir() {
        files += copy_tree(&root.join("docs/roles"), &out.join("docs/roles"))?;
    }
    // So does what a group needs to keep its folder without the repository:
    // the pattern, the skill an assistant follows, the worked example and the
    // pattern written out. The group application itself is web/group.html.
    if root.join("groups").is_dir() {
        files += copy_tree(&root.join("groups"), &out.join("groups"))?;
    }
    if root.join("docs/GROUP_FOLDER.md").is_file() {
        fs::copy(
            root.join("docs/GROUP_FOLDER.md"),
            out.join("docs/GROUP_FOLDER.md"),
        )
        .map_err(|e| format!("docs/GROUP_FOLDER.md: {e}"))?;
        files += 1;
    }
    let tree = load(root)?;
    files += copy_tree(&root.join("design"), &out.join("design"))?;
    let (_, fingerprint) = vleo_files::convert::read_folder(&out.join("design"))
        .map_err(|e| format!("the design the kit carries does not read: {e}"))?;
    // Beside it, what each node folder holds that is the code's and not the
    // design's — its generated module, contract and evidence — which a row's
    // page shows, and the prior implementation's grid (parity.csv), which a
    // page's list of gaps still looks for on disk; never the sheet or its
    // fixtures, which the design's files answer for.
    for c in fs::read_dir(root.join("crates")).map_err(|e| format!("crates: {e}"))? {
        let c = c.map_err(|e| e.to_string())?.path();
        let nodes = c.join("nodes");
        let name = c.file_name().unwrap().to_string_lossy().into_owned();
        if !name.starts_with("vleo-mod-") || !nodes.is_dir() {
            continue;
        }
        for n in fs::read_dir(&nodes).map_err(|e| format!("{}: {e}", nodes.display()))? {
            let n = n.map_err(|e| e.to_string())?.path();
            if !n.is_dir() {
                continue;
            }
            let to = out
                .join("crates")
                .join(&name)
                .join("nodes")
                .join(n.file_name().unwrap());
            for f in fs::read_dir(&n).map_err(|e| format!("{}: {e}", n.display()))? {
                let f = f.map_err(|e| e.to_string())?.path();
                let file = f.file_name().unwrap().to_string_lossy().into_owned();
                if !f.is_file() || ["node.toml", "fixtures.toml"].contains(&file.as_str()) {
                    continue;
                }
                fs::create_dir_all(&to).map_err(|e| format!("{}: {e}", to.display()))?;
                fs::copy(&f, to.join(&file)).map_err(|e| format!("{}: {e}", f.display()))?;
                files += 1;
            }
        }
    }
    // On Windows the daemon ships as `Start VLEO.exe`: the program itself is
    // what a person double-clicks, and it opens the browser because of its
    // name. No script starts it — a script launching a program is one more
    // thing an antivirus heuristic weighs against an unknown file.
    let windows = programs
        .iter()
        .any(|p| p.extension().is_some_and(|e| e == "exe"));
    for p in &programs {
        let name = p.file_name().unwrap().to_string_lossy().into_owned();
        let as_named = if name == "vleo-daemon.exe" {
            "Start VLEO.exe".to_string()
        } else {
            name
        };
        fs::copy(p, out.join(as_named)).map_err(|e| e.to_string())?;
    }
    let guide = fs::read_to_string(root.join("docs/TEAM_GUIDE.md"))
        .map_err(|e| format!("docs/TEAM_GUIDE.md: {e}"))?;
    fs::write(out.join("START_HERE.md"), guide).map_err(|e| e.to_string())?;
    let commit = std::process::Command::new("git")
        .args(["rev-parse", "--short", "HEAD"])
        .current_dir(root)
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .unwrap_or_default();
    fs::write(
        out.join("VERSION"),
        format!(
            "vleo {version}\ncommit {commit}\n{} rows\ndesign {fingerprint}\n",
            tree.sheets.len(),
        ),
    )
    .map_err(|e| e.to_string())?;
    if !files_only && !windows {
        fs::write(
            out.join("start.sh"),
            "#!/bin/sh\n# Start the tool and open it in the browser. Stop it with Ctrl-C.\n\
             cd \"$(dirname \"$0\")\" || exit 1\nexec ./vleo-daemon --open\n",
        )
        .map_err(|e| e.to_string())?;
    }
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        for f in ["start.sh", "vleo-daemon", "vleo"] {
            let p = out.join(f);
            if p.is_file() {
                let _ = fs::set_permissions(&p, fs::Permissions::from_mode(0o755));
            }
        }
    }
    let start = if files_only {
        "installs the Python package that carries it"
    } else if windows {
        "double-clicks Start VLEO.exe"
    } else {
        "runs start.sh"
    };
    println!(
        "kit: {} — vleo {version}, {} rows, {files} files beside {} program(s).\n\
         Zip that folder and share it. Each engineer unzips it, {start} \
         and reads START_HERE.md; nothing in it is edited, \
         and their case and results stay under ~/.vleo/ when the next kit replaces it.",
        out.display(),
        tree.sheets.len(),
        programs.len()
    );
    Ok(())
}

/// The three role guides, rendered from the manual (vleo_sheet::guide).
pub(super) fn cmd_guides(root: &Path) -> Result<(), String> {
    let m = vleo_sheet::manual::load(root)?;
    let version = workspace_version(root)?;
    let dir = root.join("docs").join("roles");
    fs::create_dir_all(&dir).map_err(|e| format!("{}: {e}", dir.display()))?;
    for role in vleo_sheet::manual::ROLES {
        let html = vleo_sheet::guide::render(&m, role, &version)?;
        let out = dir.join(format!("{role}.html"));
        fs::write(&out, &html).map_err(|e| format!("{}: {e}", out.display()))?;
        println!("guides: {} — {} KB", out.display(), html.len() / 1024);
    }
    Ok(())
}

/// `release <version> [--check]` — the application's version, set.
///
/// It once stamped every node version still marked `next` with the release
/// as well. That was an edit to the design, which the developer never makes:
/// a node's record is its node engineer's, and says which release carried
/// each belief when the design's own release does.
pub(super) fn cmd_release(root: &Path, args: &[&str]) -> Result<(), String> {
    use crate::pipeline::{OnStop, Run};
    use vleo_sheet::derisk::{release_key, NEXT};
    let v = args
        .iter()
        .find(|a| !a.starts_with("--"))
        .copied()
        .ok_or("usage: xtask release <version> [--check] — e.g. `release 0.2.0`")?;
    let key = release_key(v)
        .filter(|_| v != NEXT)
        .ok_or_else(|| format!("«{v}» is not a version: three numbers, like 0.2.0"))?;
    let now = workspace_version(root)?;
    let now_key =
        release_key(&now).ok_or_else(|| format!("Cargo.toml's version «{now}» is not x.y.z"))?;
    if key < now_key {
        return Err(format!(
            "{v} is older than the workspace's {now}; a release only moves forward"
        ));
    }
    if args.contains(&"--check") {
        // Only reads: the check the release pipeline runs, and --dry-run.
        if v != now {
            return Err(format!("the workspace says {now}, and the release is {v}. Run `cargo xtask release {v}` and commit"));
        }
        println!("release {v}: the workspace says {v}");
        return Ok(());
    }
    let mut run = Run::start(root, "release", args, 2);
    let again = format!("cargo run -p xtask -- release {v}");
    if v == now {
        run.skip(
            "set the workspace version",
            &format!("the workspace already says {v}"),
        );
    } else {
        run.step(
            "set the workspace version",
            OnStop::new(
                "Cargo.toml or a lock file may be changed — `git diff` shows which",
                format!("`git restore Cargo.toml Cargo.lock crates/*/Cargo.lock`, then {again}"),
            ),
            || {
                let path = root.join("Cargo.toml");
                let text = fs::read_to_string(&path).map_err(|e| format!("Cargo.toml: {e}"))?;
                let out = with_workspace_version(&text, v)?;
                fs::write(&path, out).map_err(|e| format!("Cargo.toml: {e}"))?;
                // The lock file names the workspace's own version; cargo rewrites
                // it, offline, the moment anything asks it about the workspace.
                let st = std::process::Command::new("cargo")
                    .args(["metadata", "--offline", "--format-version", "1"])
                    .current_dir(root)
                    .stdout(std::process::Stdio::null())
                    .status()
                    .map_err(|e| format!("cargo metadata: {e}"))?;
                if !st.success() {
                    return Err("cargo could not update Cargo.lock for the new version".into());
                }
                // THE CRATES OUTSIDE THE WORKSPACE KEEP LOCK FILES OF THEIR OWN,
                // and each names the workspace crates it depends on at their
                // version. Left alone they still said 0.1.0 after release 0.1.1,
                // and the pipeline's `--locked` build of the wasm face refused.
                // Every one is refreshed the same way, offline.
                let crates =
                    fs::read_dir(root.join("crates")).map_err(|e| format!("crates/: {e}"))?;
                for dir in crates.filter_map(|e| e.ok()).map(|e| e.path()) {
                    if !dir.join("Cargo.lock").is_file() {
                        continue;
                    }
                    let st = std::process::Command::new("cargo")
                        .args(["metadata", "--offline", "--format-version", "1"])
                        .current_dir(&dir)
                        .stdout(std::process::Stdio::null())
                        .status()
                        .map_err(|e| format!("cargo metadata: {e}"))?;
                    if !st.success() {
                        return Err(format!(
                            "cargo could not update {}/Cargo.lock for the new version",
                            dir.display()
                        ));
                    }
                }
                Ok(((), format!("{now} -> {v}, and every lock file")))
            },
        )?;
    }
    run.step(
        "regenerate",
        OnStop::new(
            "versioned; the generated files are part written",
            "cargo run -p xtask -- docs && cargo run -p xtask -- derisk",
        ),
        || {
            cmd_docs(root)?;
            cmd_derisk(root, &[])?;
            Ok((
                (),
                "the language page and the de-risking narrative".to_string(),
            ))
        },
    )?;
    run.done(&format!(
        "release {v}: workspace {now} -> {v}.\n\
         Next: `cargo run -p xtask -- gate && cargo test`, commit, then tag v{v}."
    ));
    Ok(())
}

/// `Cargo.toml` with `[workspace.package] version` set to `v` and nothing else
/// changed. Edited as a document, not as lines: comments, the member list and
/// every other key stay exactly as they were written.
pub(super) fn with_workspace_version(text: &str, v: &str) -> Result<String, String> {
    let mut doc: toml_edit::DocumentMut = text.parse().map_err(|e| format!("Cargo.toml: {e}"))?;
    let pkg = doc
        .get_mut("workspace")
        .and_then(|w| w.get_mut("package"))
        .and_then(|p| p.as_table_like_mut())
        .ok_or("Cargo.toml has no [workspace.package]")?;
    let old = pkg
        .get("version")
        .and_then(|i| i.as_str())
        .ok_or("Cargo.toml has no [workspace.package] version")?
        .to_string();
    pkg.insert("version", toml_edit::value(v));
    let out = doc.to_string();
    // Read back rather than trusted: the version is the one thing changed.
    if out.replacen(&format!("\"{v}\""), &format!("\"{old}\""), 1) != text {
        return Err("setting the version changed more of Cargo.toml than the version".into());
    }
    Ok(out)
}

#[cfg(test)]
mod version_edit {
    #[test]
    fn only_the_version_changes() {
        let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("..");
        let text = std::fs::read_to_string(root.join("Cargo.toml")).unwrap();
        let out = super::with_workspace_version(&text, "9.8.7").unwrap();
        let changed: Vec<_> = text
            .lines()
            .zip(out.lines())
            .filter(|(a, b)| a != b)
            .collect();
        assert_eq!(changed.len(), 1, "{changed:?}");
        assert!(changed[0].1.contains("\"9.8.7\""), "{changed:?}");
        assert_eq!(text.lines().count(), out.lines().count());
    }
}
