#!/usr/bin/env python3
"""The skeleton of a node crate, written from the tree.

One crate per owner — the management layer, the system layer, or one of the
subsystem layers. Not per discipline: `aero` and `mass` are both answering the
mass-and-aero layer's targets, and a crate split along discipline puts one
layer's rows in three places, so a change to that layer touches three crates.

These are generated rather than hand-kept because a hand-kept list of crates
drifts from the tree it is supposed to mirror, quietly, until somebody notices.
"""

import os

# The addition layers keep readable crate names; that they are additions is
# said on the tree, where a reader is, rather than encoded into a path.
ALIAS = {"x_envorbit": "envorbit", "x_closure": "closure"}

MANIFEST = """# GENERATED by tools/seed_tree.py from the tree. One crate per owner: a sibling
# this crate did not declare will not compile, which is the isolation rule made
# a manifest line rather than a convention.
[package]
name = "{crate}"
description = "RING 3 - {title}. {blurb}"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
vleo-core = {{ workspace = true }}

[build-dependencies]

[lints.rust]
unsafe_code = "forbid"
"""

LIB = """//! {title}
//!
//! {blurb}
//!
//! # Why this is its own crate
//!
//! Inside one crate `use crate::prop::..` from `power` compiles and the
//! isolation rule is unenforced. A separate crate makes it a manifest line: a
//! sibling this crate did not declare will not build. The faces still take one
//! dependency on the facade, so the compiler still sees independent units and
//! still builds them in parallel.
//!
//! # What is in here
//!
//! Nothing but generated node modules, and for most layers not even those yet.
//! Every formula lives one ring down in `vleo-core`; a node composes them in
//! its `model.rs` and holds no formula of its own, and `cargo xtask gate`
//! fails the build if one appears here.
#![forbid(unsafe_code)]

/// The nodes this layer owns. One module per folder, wired at build time.
pub mod nodes {{
    include!(concat!(env!("OUT_DIR"), "/nodes.rs"));
}}
"""


def blurb(crate, layers):
    if crate == "vleo-mod-management":
        return ("LAYER 1 - the management layer",
                "The ask, the money, the schedule, and the answer that goes back.")
    if crate == "vleo-mod-system":
        return ("LAYER 2 - the system layer",
                "What the satellite is made of, and what reads what.")
    sid = crate[len("vleo-mod-"):]
    inv = {v: k for k, v in ALIAS.items()}
    g = layers.get("l3_%s" % inv.get(sid, sid))
    label = g["label"] if g else sid
    return ("LAYER 3 - %s" % label,
            "One subsystem layer. It answers its targets from the system layer, "
            "and is reached through its interface node rather than by reaching into it.")


def emit(crates, layers, root, write, build_rs):
    for crate in crates:
        title, text = blurb(crate, layers)
        base = os.path.join(root, "crates", crate)
        write(os.path.join(base, "Cargo.toml"),
              MANIFEST.format(crate=crate, title=title, blurb=text))
        write(os.path.join(base, "build.rs"), build_rs)
        write(os.path.join(base, "src", "lib.rs"),
              LIB.format(title=title, blurb=text))

    fence(os.path.join(root, "Cargo.toml"), write,
          "    # --- node crates, generated by tools/seed_tree.py ---",
          "    # --- end node crates ---",
          "".join('    "crates/%s",\n' % c for c in crates))
    fence(os.path.join(root, "crates", "vleo-modules", "Cargo.toml"), write,
          "# --- node crates, generated by tools/seed_tree.py ---",
          "# --- end node crates ---",
          "".join('%s = { path = "../%s" }\n' % (c, c) for c in crates))


def fence(path, write, begin, end, body):
    """Rewrite one marked region of a hand-written file and nothing else.

    A generated file can be regenerated wholesale; a manifest cannot, because
    the rest of it is somebody's. Fencing the generated part keeps both true.
    """
    text = open(path, encoding="utf-8").read()
    if begin not in text or end not in text:
        raise SystemExit("%s: the generated-region markers are missing" % path)
    head = text[: text.index(begin) + len(begin) + 1]
    write(path, head + body + text[text.index(end):])
