#!/usr/bin/env python3
"""The signing checklist for the panel references, generated from the specs.

    tools/panel_review.py                  regenerate panels/REVIEW.md
    tools/panel_review.py --check          is the committed file what the specs say
    tools/panel_review.py --sheets DIR     also write contact sheets, for looking
    tools/panel_review.py --selftest

A reference is signed by hand, in its own `panels/<id>.toml`, and nothing here
changes that — `confirmed_by` is a person saying they looked, and the whole
reason it is typed rather than computed is that no check can tell a picture
somebody studied from one a machine drew unattended.

What this does is make the looking cheap: every reference image and every spec
file, gathered into one page with each panel's claim beside its two file paths.

IT IS GENERATED, AND THE GATE HOLDS IT TO THAT. Every line of it is a copy of
something in a spec — the `correct` block, the current signature — and a copy is
a thing that drifts. §21 of docs/MATLAB_PORT_PLAN.md is three copied constants
going stale in one panel; AGENTS.md carries the scar of the review standards
living in two files that had already begun to differ. So `--check` fails when
the committed file is not what the specs currently generate, which is the same
rule `docs/VARIABLES.md` lives under: sign a panel, regenerate, commit both.

The contact sheets are NOT committed. They are derivable from the references in
one command, they are a megabyte, and a thumbnail is an index rather than a
review — a chart is checked at full size.
"""

import argparse
import io
import shutil
import subprocess
import sys
import re
import tempfile
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PANELS = ROOT / "panels"
OUT = PANELS / "REVIEW.md"

# Fitted into a box rather than scaled to a width: `paths` is a 62-by-1190
# strip, and scaling that to a column width makes a tile nine thousand pixels
# tall — which is how the first version of this produced a sheet no viewer
# would accept.
BOX_W, BOX_H, PAD, LAB, PER_PAGE = 470, 380, 12, 16, 4


def specs(root=ROOT):
    out = {}
    for f in sorted((root / "panels").glob("*.toml")):
        out[f.stem] = tomllib.load(open(f, "rb"))
    return out


def render(root=ROOT):
    """The checklist, as text. Pure: same specs in, same bytes out."""
    ref = root / "panels" / "reference"
    sp = specs(root)
    # Nothing below may type a count. This page exists because a copied number
    # goes stale, and a count of the panels written into the prose of a file
    # generated FROM the panels would be the first one to do it.
    moving = sorted(p for p, d in sp.items() if d.get("interactive"))
    still = sorted(p for p in sp if p not in moving)
    L = []
    A = L.append
    A("<!-- GENERATED by tools/panel_review.py. Do not edit: the gate regenerates")
    A("     this and fails on a diff. Sign a panel in its own panels/<id>.toml,")
    A("     then re-run the tool and commit both. -->")
    A("")
    A("# Signing the panel references")
    A("")
    A("%d panels, each with a light and a dark rendering, and **a machine drew" % len(sp))
    A("every one of them.** `panels/README.md` says why that matters: the check cannot")
    A("tell a reference somebody studied from one a machine drew unattended, which is")
    A("the whole reason the name is written by hand.")
    A("")
    A("**Ticking a box in this file signs nothing.** The attestation is the")
    A("`confirmed_by` line in `panels/<id>.toml` and nowhere else. This page is a")
    A("reading aid; the boxes are for keeping your place.")
    A("")
    A("## What a machine has already established")
    A("")
    A("- All %d pass `tools/panel_check.py`: they render, they read the rows they" % len(sp))
    A("  declare, and each matches its own stored reference in both schemes.")
    A("- %d of them are `interactive` and are also driven — brushed, and their legend"
      % len(moving))
    A("  entries clicked — to check the picture actually changes. %s %s not, so"
      % (", ".join("`%s`" % p for p in still),
         "is" if len(still) == 1 else "are"))
    A("  nothing mechanical has moved %s: what you see is the whole of it."
      % ("it" if len(still) == 1 else "them"))
    A("- Every number printed inside a figure is computed from the arrays that figure")
    A("  is drawn from. None is typed. That makes them self-consistent; it does not")
    A("  make them right, which is what a reader is for.")
    A("")
    A("## What only a person can do")
    A("")
    A("Open both pictures and read the claim below them. Two things to look for in a")
    A("dark rendering that the light one will never show: a block of light where a")
    A("fill should have gone dark, and a line you have to hunt for. Both are one")
    A("defect — a value chosen against the wrong surface — and both pass every")
    A("mechanical check in this repository.")
    A("")
    A("## To sign one")
    A("")
    A("In `panels/<id>.toml`, replace the `confirmed_by` line with your name, the")
    A("date, and which renderings you looked at:")
    A("")
    A("```toml")
    A('confirmed_by = "A. Rai / 2026-09-20 (light and dark both looked at)"')
    A("```")
    A("")
    A("Then `tools/panel_review.py` to refresh this file, and commit both. Signing a")
    A("panel you have not opened is worse than leaving it UNCONFIRMED: the field")
    A("exists so a later reader knows which references were studied.")
    A("")
    A("To look at them all at once:")
    A("")
    A("```")
    A("tools/panel_review.py --sheets /tmp/sheets")
    A("```")
    A("")
    A("---")
    A("")
    unsigned = [p for p, s in sp.items()
                if "UNCONFIRMED" in str(s.get("confirmed_by", ""))]
    nofield = [p for p, s in sp.items() if "confirmed_by" not in s]
    A("**%d of %d panels are UNCONFIRMED.**" % (len(unsigned), len(sp)))
    if nofield:
        A("")
        A("%s carr%s no `confirmed_by` field at all. %s predate%s the field and %s"
          % (", ".join("`%s`" % p for p in nofield),
             "ies" if len(nofield) == 1 else "y",
             "It" if len(nofield) == 1 else "They",
             "s" if len(nofield) == 1 else "",
             "it was" if len(nofield) == 1 else "they were"))
        A("deliberately never backfilled, because nobody now remembers who looked and a")
        A("guessed attestation is worse than none.")
    A("")
    A("---")
    A("")
    for pid in sorted(sp):
        s = sp[pid]
        lp, dp = ref / ("%s.png" % pid), ref / ("%s.dark.png" % pid)
        A("## `%s` — %s" % (pid, s.get("label", "")))
        A("")
        A("- [ ] light — `%s`%s"
          % (lp.relative_to(root), "" if lp.exists() else "  **MISSING**"))
        A("- [ ] dark — `%s`%s"
          % (dp.relative_to(root), "" if dp.exists() else "  **MISSING**"))
        A("")
        A("<details><summary>what it must show (<code>correct</code>)</summary>")
        A("")
        A("```")
        A(str(s.get("correct", "(no correct block)")).rstrip())
        A("```")
        A("")
        A("</details>")
        A("")
        A("Current: `%s`" % s.get("confirmed_by", "(no confirmed_by field)"))
        A("")
        A("---")
        A("")
    return "\n".join(L) + "\n"


def sheets(into, root=ROOT):
    """Contact sheets, one page per four panels, per scheme. Not committed."""
    from PIL import Image, ImageDraw  # lazy: the gate's tools job has no Pillow

    ref = root / "panels" / "reference"
    into = Path(into)
    into.mkdir(parents=True, exist_ok=True)
    ids = sorted(specs(root))
    made = []
    for dark in (False, True):
        tag = "dark" if dark else "light"
        tiles = []
        for pid in ids:
            p = ref / ("%s%s.png" % (pid, ".dark" if dark else ""))
            if not p.is_file():
                continue
            im = Image.open(p).convert("RGB")
            k = min(BOX_W / im.width, BOX_H / im.height)
            tiles.append((pid, im.resize((max(1, round(im.width * k)),
                                          max(1, round(im.height * k))), Image.LANCZOS)))
        for page in range((len(tiles) + PER_PAGE - 1) // PER_PAGE):
            band = tiles[page * PER_PAGE:(page + 1) * PER_PAGE]
            rows = [band[i:i + 2] for i in range(0, len(band), 2)]
            hs = [max(t[1].height for t in r) + LAB + PAD for r in rows]
            bg = (20, 19, 17) if dark else (251, 250, 247)
            fg = (236, 235, 230) if dark else (26, 26, 26)
            im = Image.new("RGB", ((BOX_W + PAD * 2) * 2, sum(hs) + PAD), bg)
            d = ImageDraw.Draw(im)
            y = PAD
            for ri, r in enumerate(rows):
                for c, (pid, t) in enumerate(r):
                    x = c * (BOX_W + PAD * 2) + PAD
                    d.text((x, y), "%s  (%s)" % (pid, tag), fill=fg)
                    im.paste(t, (x, y + LAB))
                y += hs[ri]
            f = into / ("contact-%s-%d.png" % (tag, page + 1))
            im.save(f)
            made.append(f)
    for f in made:
        print("  %s" % f)
    print("%d sheet(s). They are an index — a chart is checked at full size." % len(made))


# A ticked box is a reader keeping their place, not a claim. The file says so
# in as many words, so the check has to be indifferent to it — a reading aid
# whose marks fail the build is not a reading aid, and the first reviewer to
# tick one would learn to stop marking the page rather than to sign properly.
# The attestation this check does compare is the `confirmed_by` line, which
# lives in the panel sheet and is reproduced here from it.
def _unticked(text):
    return re.sub(r"^- \[[xX]\] ", "- [ ] ", text, flags=re.M)


def check():
    want = render()
    if not OUT.is_file():
        print("panels/REVIEW.md is missing. Run tools/panel_review.py.")
        return 1
    got = io.open(OUT, encoding="utf-8").read()
    if _unticked(got) == _unticked(want):
        print("panels/REVIEW.md is what the specs say.")
        return 0
    print("panels/REVIEW.md is not what the specs generate — a spec changed and the")
    print("checklist did not. Run tools/panel_review.py and commit the result.")
    a, b = _unticked(got).splitlines(), _unticked(want).splitlines()
    for i in range(max(len(a), len(b))):
        x = a[i] if i < len(a) else "(end of file)"
        y = b[i] if i < len(b) else "(end of file)"
        if x != y:
            print("  first difference, line %d:" % (i + 1))
            print("    committed: %s" % x[:100])
            print("    generated: %s" % y[:100])
            break
    return 1


def selftest():
    """A check that cannot fail is not a check: make the specs disagree."""
    bad = 0
    with tempfile.TemporaryDirectory() as tmp:
        work = Path(tmp) / "tree"
        shutil.copytree(ROOT, work, ignore=shutil.ignore_patterns(".git", "target"))
        io.open(work / "panels" / "REVIEW.md", "w", encoding="utf-8").write(render(work))

        def run(*args):
            return subprocess.run([sys.executable, str(work / "tools" / "panel_review.py"),
                                   *args], cwd=work, capture_output=True, text=True)

        r = run("--check")
        if r.returncode != 0:
            bad += 1
            print("  FAIL a freshly generated checklist does not pass --check: %s"
                  % r.stdout.strip()[:200])

        # The page tells a reviewer the boxes are for keeping their place, so
        # ticking one must not fail the gate. This is the case that keeps that
        # promise honest.
        rv = work / "panels" / "REVIEW.md"
        t = io.open(rv, encoding="utf-8").read()
        ticked = t.replace("- [ ] light", "- [x] light", 1)
        if ticked == t:
            bad += 1
            print("  FAIL no unticked light box to tick — the checklist no longer "
                  "has the boxes this case is about, so it proves nothing")
        io.open(rv, "w", encoding="utf-8").write(ticked)
        r = run("--check")
        if r.returncode != 0:
            bad += 1
            print("  FAIL ticking a box failed --check: %s" % r.stdout.strip()[:200])
        io.open(rv, "w", encoding="utf-8").write(t)

        # A signature landing is exactly the change this has to notice.
        f = work / "panels" / "design.toml"
        s = io.open(f, encoding="utf-8").read()
        before = s
        s = s.replace("UNCONFIRMED", "A. Person / 2026-01-01", 1)
        if s == before:
            bad += 1
            print("  FAIL the patch changed nothing — design.toml no longer says "
                  "UNCONFIRMED, so this case proves nothing")
        io.open(f, "w", encoding="utf-8").write(s)
        if run("--check").returncode == 0:
            bad += 1
            print("  FAIL a panel was signed and --check still passed")

        # Every count the page states has to be read off the specs. A typed one
        # would be the first thing in this repository to go stale, and the page
        # is generated precisely so that cannot happen — so adding a panel must
        # move the number the page prints.
        probe = work / "panels" / "zz_probe.toml"
        io.open(probe, "w", encoding="utf-8").write(
            'label = "Probe"\ncorrect = "nothing; it measures the generator"\n'
            'confirmed_by = "UNCONFIRMED"\n')
        run()
        after = io.open(rv, encoding="utf-8").read()
        probe.unlink()
        n = len(specs(work))
        if ("%d panels, each with" % (n + 1)) not in after:
            bad += 1
            print("  FAIL adding a panel did not move the count the page states — "
                  "it is typed somewhere rather than read off the specs")
        if ("of %d panels are UNCONFIRMED" % (n + 1)) not in after:
            bad += 1
            print("  FAIL the UNCONFIRMED tally did not move with the panel count")

        # And regenerating has to settle it again.
        run()
        if run("--check").returncode != 0:
            bad += 1
            print("  FAIL regenerating did not bring the checklist back into line")
    print("selftest: 5 cases, %s" % ("all as expected" if not bad else "%d FAILED" % bad))
    return 1 if bad else 0


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--sheets")
    a = ap.parse_args()
    if a.selftest:
        return selftest()
    if a.check:
        return check()
    io.open(OUT, "w", encoding="utf-8").write(render())
    print("panel review: %d panel(s) -> %s" % (len(specs()), OUT.relative_to(ROOT)))
    if a.sheets:
        sheets(a.sheets)
    return 0


if __name__ == "__main__":
    sys.exit(main())
