#!/usr/bin/env python3
"""Write docs/SOLAR_ROWS.md: what every live solar row is, and where it came from.

Generated, because a classification maintained by hand is a classification that
is wrong. Three questions are answered for each row, and each is answered by
measurement rather than by reading a label:

  WHERE IT CAME FROM. The MATLAB study publishes one thing -- a driver set of
  five scenarios over f107, f107bar, ap, kp_mean and kp_peak, twenty-five
  numbers, in matlab/reference/mission_drivers.csv. A row is part of that port
  if l3_solar_interface reaches it. A row can also carry the study's relation
  and sit OUTSIDE the chain, because the relation was moved into vleo-core so a
  driver set could evaluate it at five scenarios rather than one; those rows are
  the provenance of a kernel constant and compute nothing live. Everything else
  is extra -- a question this tree asks that the study did not.

  WHAT IT DOES. Its own question, as the sheet states it.

  WHETHER IT IS A NUMBER OR A CURVE. Every row answers with one number; the
  question is whether anything moves it. A row with no upstream decision that
  changes its answer is a fixed number and a graph of it is a flat line. A row
  with one is a curve, and the decision that moves it most is named. Measured
  through /v1/levers, so a term that is in the relation and inert is counted as
  inert.

Needs the daemon: cargo run --release -p vleo-daemon
"""
import json, os, re, glob, sys, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "http://127.0.0.1:7777"


def get(path):
    return json.loads(urllib.request.urlopen(BASE + path).read())


def main():
    idx = json.load(open(os.path.join(ROOT, "generated/index.json")))
    rows = idx["rows"]
    byi = {r["i"]: r for r in rows}
    byid = {r["id"]: r for r in rows}
    prod = {r["i"]: r["in"] for r in rows}

    def ancestors(nid):
        seen, st = set(), [byid[nid]["i"]]
        while st:
            n = st.pop()
            for p in prod.get(n, []):
                if p not in seen:
                    seen.add(p)
                    st.append(p)
        return {byi[i]["id"] for i in seen}

    chain = ancestors("l3_solar_interface") | {"l3_solar_interface"}

    # Which panel draws which row.
    drawn = {}
    for p in glob.glob(os.path.join(ROOT, "web/js/*.js")) + glob.glob(os.path.join(ROOT, "panels/*.toml")):
        txt = open(p, encoding="utf-8").read()
        for m in re.finditer(r"id:\s*'([a-z0-9_]+)',\s*\n\s*rows:\s*\[([^\]]*)\]", txt):
            panel, body = m.group(1), m.group(2)
            for rid in re.findall(r"'([a-z0-9_.]+)'", body):
                drawn.setdefault(rid, []).append(panel)

    solar = [r for r in rows
             if (r["id"].startswith("sw_") or r["id"].startswith("l3_solar"))
             and r["state"] != "deprecated"]
    solar.sort(key=lambda r: r["i"])

    out = [
        "# The solar subsystem, row by row\n",
        "Generated by `tools/solar_rows.py`. Do not edit by hand.\n",
        "\n## Where the three origins come from\n",
        "\n**Ported** — the row is part of the chain that produces the study's driver set.",
        "`l3_solar_interface` reaches it, and the study's own output",
        "(`matlab/reference/mission_drivers.csv`) is twenty-five numbers: five scenarios",
        "over f107, f107bar, ap, kp_mean and kp_peak.\n",
        "\n**Kernel** — the row carries the study's relation but computes nothing live.",
        "Its relation moved into `vleo-core` so a driver set could evaluate it at five",
        "scenarios rather than one; the row remains as the provenance of that constant.\n",
        "\n**Extra** — a question this tree asks that the study did not.\n",
        "\n`✓` in the parity column means the row holds a `parity.csv`: the MATLAB tool's",
        "own answer, recorded as a second opinion rather than as a fixture.\n",
    ]

    groups = [("Ported", []), ("Kernel", []), ("Extra", [])]
    for r in solar:
        nid = r["id"]
        par = os.path.exists(os.path.join(ROOT, "crates/vleo-mod-solar/nodes/%s/parity.csv" % nid))
        if nid in chain:
            where = "Ported"
        elif par:
            where = "Kernel"
        else:
            where = "Extra"
        try:
            lv = get("/v1/levers?node=" + nid).get("levers", [])
        except Exception:
            lv = []
        moves = [l for l in lv if l.get("span") is not None and l["span"] > 0]
        inert = [l for l in lv if l.get("span") == 0]
        blocked = [l for l in lv if l.get("span") is None]
        if r["kind"] == "declared":
            shape = "**number** — a decision; it is what moves other rows"
        elif moves:
            top = moves[0]
            shape = "**curve** over `%s` (%s)" % (top["id"], pct(top["span"]))
            if len(moves) > 1:
                shape += ", and %d more" % (len(moves) - 1)
        elif blocked:
            # Not the same fact as an inert decision, and collapsing the two is
            # exactly the error this report was written to stop repeating.
            shape = ("**number here** — the %d decision(s) upstream refuse at a range end, "
                     "so no curve can be drawn without narrowing one" % len(blocked))
        elif inert:
            shape = "**number** — all %d decisions upstream leave it unchanged" % len(inert)
        else:
            shape = "**number** — no decision upstream of it at all"
        panels = drawn.get(nid, [])
        val = "%.6g" % r["value"] if r["value"] is not None else "computed"
        dict(groups)[where].append(
            "| `%s` | %s | %s | %s | %s | %s |"
            % (nid, r["label"], val, shape, ", ".join(sorted(set(panels))) or "—",
               "✓" if par else "")
        )

    # The summary is the finding, so it goes first. Counting which rows a figure
    # draws is the fact that decides what can be removed, and it is not the fact
    # anyone would have guessed.
    ported = [r for r in solar if r["id"] in chain]
    undrawn = [r["id"] for r in solar if not drawn.get(r["id"])]
    pan_ported = {p for r in ported for p in drawn.get(r["id"], [])}
    pan_other = {p for r in solar if r["id"] not in chain for p in drawn.get(r["id"], [])}
    out.append("\n## What this adds up to\n\n")
    out.append("The port of the study is **%d rows**. The other **%d** are questions this "
               "tree added.\n\n" % (len(ported), len(solar) - len(ported)))
    out.append("Between them the %d ported rows are drawn by **%d** figure%s (%s). The %d extra "
               "rows are drawn by **%d** (%s). Nearly every figure in this subsystem draws a row "
               "the study never had — so removing the extras removes the pictures, and the rows "
               "that reproduce the study are the ones with almost nothing drawn of them.\n\n"
               % (len(ported), len(pan_ported), "" if len(pan_ported) == 1 else "s",
                  ", ".join(sorted(pan_ported)) or "none",
                  len(solar) - len(ported), len(pan_other), ", ".join(sorted(pan_other)) or "none"))
    out.append("**%d rows are drawn by nothing at all**, and those are where a removal costs "
               "least: %s.\n" % (len(undrawn), ", ".join("`%s`" % x for x in undrawn)))
    for name, body in groups:
        out.append("\n## %s — %d rows\n\n" % (name, len(body)))
        out.append("| row | what it answers | value | number or curve | drawn in | parity |\n")
        out.append("|---|---|---|---|---|---|\n")
        out.append("\n".join(body) + "\n")

    p = os.path.join(ROOT, "docs/SOLAR_ROWS.md")
    open(p, "w", encoding="utf-8").write("".join(out))
    print("solar rows: %d live -> %s" % (len(solar), p))
    for name, body in groups:
        print("  %-8s %d" % (name, len(body)))
    return 0


def pct(v):
    return "%d%%" % round(v * 100) if v >= 0.1 else "%.2f%%" % (v * 100)


if __name__ == "__main__":
    sys.exit(main())
