#!/usr/bin/env python3
"""Write docs/SOLAR_ROWS.md: what every live solar row is, and where it came from.

Generated, because a classification maintained by hand is a classification that
is wrong. Three questions are answered for each row, and each is answered by
measurement rather than by reading a label:

  WHERE IT CAME FROM. The MATLAB study publishes one thing -- a driver set of
  five scenarios over f107, f107bar, ap, kp_mean and kp_peak, twenty-five
  numbers, in matlab/reference/mission_drivers.csv. A row is part of that port
  if l3_solar_interface reaches it. A row can also carry the study's relation
  and sit OUTSIDE the chain, because the relation was moved into vleo-core so a
  driver set could evaluate it at five scenarios rather than one; those rows are
  the provenance of a kernel constant and compute nothing live. Everything else
  is extra -- a question this tree asks that the study did not.

  WHAT IT DOES. Its own question, as the sheet states it.

  WHETHER IT IS A NUMBER OR A CURVE. Every row answers with one number; the
  question is whether anything moves it. A row with no upstream decision that
  changes its answer is a fixed number and a graph of it is a flat line. A row
  with one is a curve, and the decision that moves it most is named. Measured
  through /v1/levers, so a term that is in the relation and inert is counted as
  inert.

Needs the daemon: cargo run --release -p vleo-daemon
"""
import json, os, re, glob, sys, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = "http://127.0.0.1:7777"


def get(path):
    return json.loads(urllib.request.urlopen(BASE + path).read())


def main():
    idx = json.load(open(os.path.join(ROOT, "generated/index.json")))
    rows = idx["rows"]
    byi = {r["i"]: r for r in rows}
    byid = {r["id"]: r for r in rows}
    prod = {r["i"]: r["in"] for r in rows}

    def ancestors(nid):
        seen, st = set(), [byid[nid]["i"]]
        while st:
            n = st.pop()
            for p in prod.get(n, []):
                if p not in seen:
                    seen.add(p)
                    st.append(p)
        return {byi[i]["id"] for i in seen}

    chain = ancestors("l3_solar_interface") | {"l3_solar_interface"}

    # Which panel draws which row.
    drawn = {}
    for p in glob.glob(os.path.join(ROOT, "web/js/*.js")) + glob.glob(os.path.join(ROOT, "panels/*.toml")):
        txt = open(p, encoding="utf-8").read()
        for m in re.finditer(r"id:\s*'([a-z0-9_]+)',\s*\n\s*rows:\s*\[([^\]]*)\]", txt):
            panel, body = m.group(1), m.group(2)
            for rid in re.findall(r"'([a-z0-9_.]+)'", body):
                drawn.setdefault(rid, []).append(panel)

    solar = [r for r in rows
             if (r["id"].startswith("sw_") or r["id"].startswith("l3_solar"))
             and r["state"] != "deprecated"]
    solar.sort(key=lambda r: r["i"])

    out = [
        "# The solar subsystem, row by row\n",
        "Generated by `tools/solar_rows.py`. Do not edit by hand.\n",
        "\n## Where the three origins come from\n",
        "\n**Ported** — the row is part of the chain that produces the study's driver set.",
        "`l3_solar_interface` reaches it, and the study's own output",
        "(`matlab/reference/mission_drivers.csv`) is twenty-five numbers: five scenarios",
        "over f107, f107bar, ap, kp_mean and kp_peak.\n",
        "\n**Kernel** — the row carries the study's relation but computes nothing live.",
        "Its relation moved into `vleo-core` so a driver set could evaluate it at five",
        "scenarios rather than one; the row remains as the provenance of that constant.\n",
        "\n**Extra** — a question this tree asks that the study did not.\n",
        "\n`✓` in the parity column means the row holds a `parity.csv`: the MATLAB tool's",
        "own answer, recorded as a second opinion rather than as a fixture.\n",
    ]

    # WHAT A ROW COSTS TO REMOVE. Three facts decide it, in this order:
    #   - another live row reads it        -> removing it breaks that row
    #   - a figure draws it                -> removing it costs a picture
    #   - it is the port of the study      -> removing it is removing the point
    # Anything none of those touch is free to go.
    readers = {}
    for r in rows:
        if r["state"] == "deprecated":
            continue
        for pi in r["in"]:
            readers.setdefault(byi[pi]["id"], []).append(r["id"])

    # A row kept only because a removable row reads it is not really kept: take
    # the reader out and it is orphaned. So the free set is grown to a fixed
    # point -- a row joins it when every one of its readers has already joined.
    # Without this the table says "remove l3_solar_ach_01, keep l3_solar_req_01",
    # which leaves a requirement nothing closes.
    free = set()
    while True:
        added = False
        for r in solar:
            nid = r["id"]
            if nid in free or nid in chain or drawn.get(nid):
                continue
            rd = [x for x in readers.get(nid, []) if x != nid]
            if all(x in free for x in rd):
                free.add(nid)
                added = True
        if not added:
            break

    def verdict(r):
        nid = r["id"]
        rd = sorted(x for x in readers.get(nid, []) if x != nid)
        fig = drawn.get(nid, [])
        if nid in free:
            others = [x for x in rd if x in free]
            if others:
                return ("EASY, AS A PAIR",
                        "free only if %s goes with it — it is read by nothing else"
                        % ", ".join("`%s`" % x for x in others))
            return ("EASY", "nothing reads it and no figure draws it")
        if rd:
            return ("KEEP", "%d live row%s read it: %s"
                    % (len(rd), "" if len(rd) == 1 else "s",
                       ", ".join("`%s`" % x for x in rd[:4])))
        if nid in chain:
            return ("KEEP", "it is the port of the study's driver set")
        if fig:
            return ("COSTS A FIGURE", "the %s panel draws it; removing it means rewriting that panel"
                    % "/".join(sorted(set(fig))))
        return ("EASY", "nothing reads it and no figure draws it")

    def table(items):
        out = ["| row | what it answers | value | number or curve | remove? | why |\n",
               "|---|---|---|---|---|---|\n"]
        for r, shape, par in items:
            v, why = verdict(r)
            val = "%.6g" % r["value"] if r["value"] is not None else "computed"
            out.append("| `%s`%s | %s | %s | %s | **%s** | %s |\n"
                       % (r["id"], " ✓" if par else "", r["label"], val, shape, v, why))
        return "".join(out)

    described = []
    for r in solar:
        nid = r["id"]
        par = os.path.exists(os.path.join(ROOT, "crates/vleo-mod-solar/nodes/%s/parity.csv" % nid))
        try:
            lv = get("/v1/levers?node=" + nid).get("levers", [])
        except Exception:
            lv = []
        moves = [l for l in lv if l.get("span") is not None and l["span"] > 0]
        inert = [l for l in lv if l.get("span") == 0]
        blocked = [l for l in lv if l.get("span") is None]
        if r["kind"] == "declared":
            shape = "**number** — a decision; it is what moves other rows"
        elif moves:
            shape = "**curve** over `%s` (%s)" % (moves[0]["id"], pct(moves[0]["span"]))
            if len(moves) > 1:
                shape += ", +%d" % (len(moves) - 1)
        elif blocked:
            shape = "**number here** — %d upstream decision(s) refuse at a range end" % len(blocked)
        elif inert:
            shape = "**number** — all %d decisions upstream leave it unchanged" % len(inert)
        else:
            shape = "**number** — no decision upstream at all"
        described.append((r, shape, par))

    extra = [d for d in described if d[0]["id"] not in chain]
    port = [d for d in described if d[0]["id"] in chain]
    ex_fig = [d for d in extra if drawn.get(d[0]["id"])]
    ex_non = [d for d in extra if not drawn.get(d[0]["id"])]
    po_fig = [d for d in port if drawn.get(d[0]["id"])]
    po_non = [d for d in port if not drawn.get(d[0]["id"])]
    easy = sorted(free)

    out.append("\n## What this adds up to\n\n")
    out.append("**No row here duplicates another.** Each was swept over seven drivers across "
               "their declared ranges and fingerprinted on the result; all %d fingerprints are "
               "distinct. So nothing is removable on the grounds of being a repeat — the only "
               "question left for each row is whether its question is worth asking.\n\n"
               % len(solar))
    out.append("| | with a figure | with no figure | total |\n|---|---|---|---|\n")
    out.append("| **Extra** — questions this tree added | %d | %d | %d |\n"
               % (len(ex_fig), len(ex_non), len(extra)))
    out.append("| **MATLAB** — the port of the study | %d | %d | %d |\n"
               % (len(po_fig), len(po_non), len(port)))
    out.append("\nThe shape of that table is the finding. Nearly every figure in this subsystem "
               "draws a row the study never had, and nearly every row that reproduces the study "
               "has no picture of it. Cutting extras costs pictures; the port is what is "
               "undrawn.\n\n")
    out.append("**%d rows are free to remove** — no figure draws them, they are not the port, and "
               "nothing outside the set reads them. They come out together: %s.\n"
               % (len(easy), ", ".join("`%s`" % x for x in easy) if easy else "none"))

    out.append("\n---\n\n# EXTRA — %d rows the study never had\n" % len(extra))
    out.append("\n## Extra, drawn by a figure — %d rows\n\n" % len(ex_fig))
    out.append("Removing any of these means rewriting the panel that draws it.\n\n")
    out.append(table(ex_fig))
    out.append("\n## Extra, no figure — %d rows\n\n" % len(ex_non))
    out.append("The cheapest removals in the subsystem, except where another row reads them.\n\n")
    out.append(table(ex_non))

    out.append("\n---\n\n# MATLAB — %d rows that port the study\n" % len(port))
    out.append("\nThese produce the twenty-five numbers of the driver set. `✓` marks a "
               "`parity.csv`: the MATLAB tool's own answer, kept as a second opinion rather than "
               "as a fixture. **None of these should be removed** — together they are the port, "
               "and the tree has nothing else that answers what they answer.\n")
    out.append("\n## Ported, drawn by a figure — %d rows\n\n" % len(po_fig))
    out.append(table(po_fig))
    out.append("\n## Ported, no figure — %d rows\n\n" % len(po_non))
    out.append("Not removal candidates. This is the list of figures that have not been drawn "
               "yet.\n\n")
    out.append(table(po_non))

    out.append("\n---\n\n## The two kernel rows\n\n")
    out.append("`sw_kp_from_ap` and `sw_regime` carry the study's relation but compute nothing "
               "live: the relation moved into `vleo-core` so a driver set could evaluate it at "
               "five scenarios rather than one. They sit under EXTRA above because "
               "`l3_solar_interface` does not reach them, and they are the provenance of a kernel "
               "constant rather than dead weight.\n")

    p = os.path.join(ROOT, "docs/SOLAR_ROWS.md")
    open(p, "w", encoding="utf-8").write("".join(out))
    print("solar rows: %d live -> %s" % (len(solar), p))
    print("  extra  %d (%d drawn, %d not)" % (len(extra), len(ex_fig), len(ex_non)))
    print("  matlab %d (%d drawn, %d not)" % (len(port), len(po_fig), len(po_non)))
    print("  free to remove: %d" % len(easy))
    return 0


def pct(v):
    return "%d%%" % round(v * 100) if v >= 0.1 else "%.2f%%" % (v * 100)


if __name__ == "__main__":
    sys.exit(main())
