//! GENERATED by `cargo xtask docs`: every node's method, translated by rule
//! into the kernel (crates/vleo-sheet/src/method.rs). One module per node that
//! has a method; a node without one keeps its hand-written holes.
