//! GENERATED by `cargo xtask docs`: every node's method, translated by rule
//! into the kernel (crates/vleo-sheet/src/method.rs). One module per node that
//! has a method; a node without one keeps its hand-written holes.

pub mod sw_activity_band;
pub mod sw_ap_cold_long;
pub mod sw_ap_cold_short;
pub mod sw_ap_daily_band_drop;
pub mod sw_ap_daily_band_spread;
pub mod sw_ap_design;
pub mod sw_ap_design_long;
pub mod sw_ap_design_short;
pub mod sw_central_expectation;
pub mod sw_cycle_phase;
pub mod sw_daily_band_drop;
pub mod sw_daily_band_spread;
pub mod sw_design_safe_duration;
pub mod sw_exceedance_duration;
pub mod sw_exceedance_phase;
pub mod sw_exceedance_rate;
pub mod sw_f107_cold_long;
pub mod sw_f107_cold_short;
pub mod sw_f107_design_long;
pub mod sw_f107_design_short;
pub mod sw_forecast_bias;
pub mod sw_forecast_skill;
pub mod sw_horizon_climatology;
pub mod sw_horizon_persistence;
pub mod sw_kp_from_ap;
pub mod sw_kp_scenarios;
pub mod sw_kp_slot_bias;
pub mod sw_mean_cycle_level;
pub mod sw_regime;
pub mod sw_storm_return_level;
pub mod sw_uncertainty_growth;
pub mod sw_window_peak_level;
