//! What a node's content means, wherever it is read: the sheet.
//!
//! A sheet is one node as the tools read it — its ports, its method, its
//! cases, its explanation and its de-risking record. Its home is the design's
//! files, `design/`: `vleo_files::convert` opens them and serves them to the
//! loader here ([`load`], through [`files::Files`]), so no sheet is written by
//! hand any more and none is kept on disk.
//!
//! This crate is the single implementation of what a sheet *means*: the
//! model, the per-node checks the gate makes, the method language the
//! interpreter runs, the node's page, the gap pass, the manual, the guides,
//! the lessons and the de-risking narrative. The commands in `xtask`, the
//! server, the command line, the engine's graph (`vleo_modules::opened`) and
//! the pages' checkers all read it, so no face carries a second copy that
//! could disagree. Two implementations of that would be two standards.
//!
//! # Two rules what is printed from it is held to
//!
//! * **What is printed for one node never reads another.** A node's page, its
//!   gap pass and its checks are one node's, so five engineers' nodes change
//!   on the same afternoon and no output is touched twice.
//! * **What is assembled never decides anything.** The index and the
//!   catalogue combine and they refuse. A decision taken during assembly is a
//!   decision nobody reviewed, because assembly has no diff.

pub mod derisk;
pub mod emit;
mod error;
pub use error::{Error, ErrorKind};
pub mod catalogue;
pub mod example;
pub mod files;
pub mod form;
pub mod guide;
pub mod lesson;
pub mod lesson_form;
pub mod manual;
pub mod method;

/// Whether this names a quantity type a sheet may declare.
pub fn is_quantity_name(n: &str) -> bool {
    vleo_units::is_quantity(n)
}

/// Every unit name, for a face to offer.
///
/// `Unit` is `#[non_exhaustive]` and its variants are generated by a macro, so
/// the names are recovered by asking `from_name` about the list the enum
/// documents. Kept beside `unit_exists` so the two cannot disagree about what
/// a unit is.
pub fn unit_names() -> Vec<&'static str> {
    vleo_units::Unit::NAMES.to_vec()
}

/// Whether this names a unit the system knows.
pub fn unit_exists(n: &str) -> bool {
    vleo_units::Unit::from_name(n).is_some()
}
pub mod gate;
pub mod load;
pub mod model;
pub mod page;
pub mod shell;
pub mod template;
pub mod text;
pub mod wiring;

pub use load::Tree;
pub use model::{Assumption, Fixture, Sheet, Step, View};

/// FNV-1a, the same function the kernel uses, so a hash written by a generator
/// and a hash computed by the engine are the same number.
pub fn fnv1a(s: &str) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for b in s.as_bytes() {
        h ^= *b as u64;
        h = h.wrapping_mul(0x0000_0100_0000_01B3);
    }
    h
}

pub fn short_hex(h: u64) -> String {
    format!("{:06x}", h & 0xff_ffff)
}
